# Generated by Django 4.1.2 on 2022-10-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_group_node_fk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupNote',
            new_name='Label',
        ),
        migrations.RemoveField(
            model_name='note',
            name='group_node_fk',
        ),
        migrations.AddField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(to='notes.label'),
        ),
    ]
